name: Build and Test Deadwood App

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.2'

      - name: Cache app dependencies
        uses: actions/cache@v3
        with:
          path: deadwoodblog/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('deadwoodblog/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: |
          cd deadwoodblog
          yarn install

      - name: Build app
        run: |
          start=$(date +%s%N)
          cd deadwoodblog
          yarn rw build
          end=$(date +%s%N)
          duration=$((($end - $start)/1000000))
        env:
          STATSD_TIMING: duration-build

      - name: Run tests
        run: |
          start=$(date +%s%N)
          cd deadwoodblog
          yarn rw test
          end=$(date +%s%N)
          duration=$((($end - $start)/1000000))
        env:
          STATSD_TIMING: duration-test

      - name: Send metrics to Statsd
        run: |
          echo "${{ env.STATSD_TIMING }}:${{ steps[env.STATSD_TIMING].outputs[env.STATSD_TIMING] }}|ms" | nc -w 1 ec2-35-90-12-71.us-west-2.compute.amazonaws.com 8125
